/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication;

/**
 * @author vmadmin
 */
public class Panel_Beispiel extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Beispiel
     */
    public Panel_Beispiel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel1.setText("Continue as Manager (F1)");

        jLabel2.setText("Continue as Kaufmann (F2)");

        jLabel3.setText("Continue as Putzfrau (F3)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Bankenmanagement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(layout.createSequentialGroup()
                                                                      .addContainerGap()
                                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                      .addComponent(jLabel1)
                                                                                      .addComponent(jLabel2)
                                                                                      .addComponent(jLabel3)))
                                                      .addGroup(layout.createSequentialGroup()
                                                                      .addGap(113, 113, 113)
                                                                      .addComponent(jLabel4)))
                                      .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                                      .addGap(27, 27, 27)
                                      .addComponent(jLabel4)
                                      .addGap(27, 27, 27)
                                      .addComponent(jLabel1)
                                      .addGap(18, 18, 18)
                                      .addComponent(jLabel2)
                                      .addGap(18, 18, 18)
                                      .addComponent(jLabel3)
                                      .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton  jButton1;
    private javax.swing.JLabel   jLabel1;
    private javax.swing.JLabel   jLabel2;
    private javax.swing.JLabel   jLabel3;
    private javax.swing.JLabel   jLabel4;
    private javax.swing.JMenu    jMenu1;
    private javax.swing.JMenu    jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
